spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000
    pool:
      max-active: 200
      max-wait: -1
      min-idle: 0
      max-idle: 10
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s
file:
  server:
    url: http://localhost:8080/uploads



